export const ACTION_FAILED = 'The application could not execute this action, please try again'
export const UPDATE_TAGS_SUCCESS = 'The tag was updated successfully'
export const DELETE_TAGS_SUCCESS = 'The tags were deleted successfully'
export const UPDATE_TAGS_ERROR = 'Tags could not be changed'
export const DELETE_TAGS_ERROR = 'Tags could not be deleted'
export const NOTHING_TO_CHANGE = 'There is nothing to change'
